-- Seed product colors from the provided color catalog.

INSERT INTO "product_colors" (
  "key",
  "label",
  "value",
  "created_at",
  "updated_at"
)
VALUES
  ('SIKACERAM_MAHOGANY', $$Mogano$$, '#6B3E2E', now(), now()),
  ('SIKACERAM_RUBY', $$Rubino$$, '#8B2E3C', now(), now()),
  ('SIKACERAM_TERRACOTTA', $$Cotto$$, '#B5654D', now(), now()),
  ('SIKACERAM_AMARANTH', $$Amaranto$$, '#8E4A57', now(), now()),
  ('SIKACERAM_BROWN', $$Marrone$$, '#7A5A46', now(), now()),
  ('SIKACERAM_OAK_WOOD', $$Legno di quercia$$, '#8B6A4E', now(), now()),
  ('SIKACERAM_WALNUT', $$Noce$$, '#6F4E37', now(), now()),
  ('SIKACERAM_BEECH_WOOD', $$Legno di faggio$$, '#B08A67', now(), now()),
  ('SIKACERAM_CARAMEL', $$Caramel$$, '#B67A3C', now(), now()),
  ('SIKACERAM_CEDAR', $$Cedro$$, '#8A5A3B', now(), now()),
  ('SIKACERAM_TORTORA', $$Tortora$$, '#9A8F84', now(), now()),
  ('SIKACERAM_GREY', $$Grigio$$, '#7D7F7D', now(), now()),
  ('SIKACERAM_LIGHT_SAND', $$Sabbia chiara$$, '#D8C7A3', now(), now()),
  ('SIKACERAM_PINE', $$Pino$$, '#C4B08A', now(), now()),
  ('SIKACERAM_MAPLE_WOOD', $$Legno d'acero$$, '#C79E6E', now(), now()),
  ('SIKACERAM_ANEMONE', $$Anemone$$, '#D8D0C4', now(), now()),
  ('SIKACERAM_BEIGE', $$Beige$$, '#D9C9A5', now(), now()),
  ('SIKACERAM_JASMINE', $$Jasmine$$, '#F0E7D5', now(), now()),
  ('SIKACERAM_WHITE', $$Bianco$$, '#F5F5F2', now(), now()),
  ('SIKACERAM_PERGAMON', $$Pergamon$$, '#E8DFCF', now(), now()),
  ('SIKACERAM_SILVER', $$Silver$$, '#BFC3C7', now(), now()),
  ('SIKACERAM_LIGHT_GREY', $$Grigio chiaro$$, '#C9C9C4', now(), now()),
  ('SIKACERAM_ICE', $$Ghiaccio$$, '#DDE3E6', now(), now()),
  ('SIKACERAM_MANHATTAN', $$Manhattan$$, '#A6A8A6', now(), now()),
  ('SIKACERAM_SAND', $$Sabbia$$, '#BFA77F', now(), now()),
  ('SIKACERAM_ASH', $$Cenere$$, '#8B8F8A', now(), now()),
  ('SIKACERAM_GRAPHITE', $$Grafite$$, '#4F5357', now(), now()),
  ('SIKACERAM_ANTHRACITE', $$Antracite$$, '#3E4347', now(), now()),
  ('SIKACERAM_TOTAL_BLACK', $$Nero assoluto$$, '#1E1E1C', now(), now()),
  ('DEUTSCH_ANTHRACITE_37', $$Anthracite 37$$, '#2B2B2B', now(), now()),
  ('DEUTSCH_BEIGE_18', $$Beige 18$$, '#D8C3A5', now(), now()),
  ('DEUTSCH_WHITE_INTENSE', $$Blanc Intense$$, '#F5F5F5', now(), now()),
  ('DEUTSCH_WHITE_01', $$Blanc 01$$, '#FFFFFF', now(), now()),
  ('DEUTSCH_DARK_BLUE_24', $$Dark Blue 24$$, '#1F3A5F', now(), now()),
  ('DEUTSCH_LIGHT_GREY_05', $$Gris Clair 05$$, '#C9C9C9', now(), now()),
  ('DEUTSCH_GREY_17', $$Gris Moyen 17$$, '#8A8A8A', now(), now()),
  ('DEUTSCH_LIGHT_BLUE_33', $$Light Blue 33$$, '#6FA3D2', now(), now()),
  ('DEUTSCH_LIGHT_GREY_INTENSE_05', $$Light Grey 05 Intense$$, '#BEBEBE', now(), now()),
  ('DEUTSCH_MAGNOLIA_13', $$Magnolia / Ivoir 13$$, '#F2E6C9', now(), now()),
  ('DEUTSCH_MYKONOS_BLUE_30', $$Mykonos Blue 30$$, '#2E5C8A', now(), now()),
  ('DEUTSCH_SILVER_GREY_16', $$Silver Grey 16$$, '#A6A6A6', now(), now()),
  ('DEUTSCH_TORTILLA_34', $$Tortilla 34$$, '#C8A97E', now(), now()),
  ('DEUTSCH_CYPRESS_GREEN_32', $$Vert Cypress 32$$, '#3F5F4A', now(), now()),
  ('DEUTSCH_SPATORELLA_BLUE', $$Bleu$$, '#282F98', now(), now()),
  ('DEUTSCH_SPATORELLA_RED', $$Rouge$$, '#FF1F35', now(), now()),
  ('SILVER', $$Argent$$, '#CCCCCC', now(), now())
ON CONFLICT ("key") DO UPDATE SET
  "label" = EXCLUDED."label",
  "value" = EXCLUDED."value",
  "updated_at" = now();
