import type { StaffSession } from "@/features/auth/types";
import { hasAnyPermission, hasPermission } from "@/features/rbac/access";
import { PERMISSIONS } from "@/features/rbac/permissions";

export function canAccessArticles(session: StaffSession): boolean {
  return hasAnyPermission(session, [
    PERMISSIONS.ARTICLES_VIEW_ALL,
    PERMISSIONS.ARTICLES_VIEW_OWN,
    PERMISSIONS.ARTICLES_CREATE,
    PERMISSIONS.ARTICLES_UPDATE_ALL,
    PERMISSIONS.ARTICLES_UPDATE_BELOW_ROLE,
    PERMISSIONS.ARTICLES_UPDATE_OWN,
    PERMISSIONS.ARTICLES_DELETE_ALL,
    PERMISSIONS.ARTICLES_DELETE_BELOW_ROLE,
    PERMISSIONS.ARTICLES_DELETE_OWN,
    PERMISSIONS.ARTICLES_PUBLISH_ALL,
    PERMISSIONS.ARTICLES_PUBLISH_BELOW_ROLE,
    PERMISSIONS.ARTICLES_PUBLISH_OWN,
    PERMISSIONS.ARTICLES_UNPUBLISH_ALL,
    PERMISSIONS.ARTICLES_UNPUBLISH_BELOW_ROLE,
    PERMISSIONS.ARTICLES_UNPUBLISH_OWN,
    PERMISSIONS.ARTICLES_AUTHORS_UPDATE_ALL,
    PERMISSIONS.ARTICLES_AUTHORS_UPDATE_BELOW_ROLE,
    PERMISSIONS.ARTICLES_AUTHORS_UPDATE_OWN,
  ]);
}

export function canCreateArticles(session: StaffSession): boolean {
  return hasPermission(session, PERMISSIONS.ARTICLES_CREATE);
}
