GET http://localhost:3000/api/staff/articles/7
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJjbW10M3c4b2IwMDAwYzBnOWl4NWYwMzkzIiwiZW1haWwiOiJhZG1pbkBjb2JhbWdyb3VwLmNvbSIsInJvbGUiOiJBZG1pbiIsInBvcnRhbCI6InN0YWZmIiwiaWF0IjoxNzczNjY0NzQ5LCJleHAiOjE3NzM2NjY1NDl9.37Iin_6QFl6mTNa-PXBBOKtvZza4nLFVmyVV2E6rkVM
Accept: application/json