import type { StaffSession } from "@/features/auth/types";
import { hasAnyPermission, hasPermission } from "@/features/rbac/access";
import { PERMISSIONS } from "@/features/rbac/permissions";

export function canAccessProducts(session: StaffSession): boolean {
  return hasAnyPermission(session, [
    PERMISSIONS.PRODUCTS_VIEW_ALL,
    PERMISSIONS.PRODUCTS_VIEW_OWN,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_UPDATE_ALL,
    PERMISSIONS.PRODUCTS_UPDATE_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_UPDATE_OWN,
    PERMISSIONS.PRODUCTS_DELETE_ALL,
    PERMISSIONS.PRODUCTS_DELETE_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_DELETE_OWN,
    PERMISSIONS.PRODUCTS_FEATURE_ALL,
    PERMISSIONS.PRODUCTS_FEATURE_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_FEATURE_OWN,
    PERMISSIONS.PRODUCTS_UNFEATURE_ALL,
    PERMISSIONS.PRODUCTS_UNFEATURE_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_UNFEATURE_OWN,
    PERMISSIONS.PRODUCTS_PUBLISH_ALL,
    PERMISSIONS.PRODUCTS_PUBLISH_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_PUBLISH_OWN,
    PERMISSIONS.PRODUCTS_UNPUBLISH_ALL,
    PERMISSIONS.PRODUCTS_UNPUBLISH_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_UNPUBLISH_OWN,
  ]);
}

export function canCreateProducts(session: StaffSession): boolean {
  return hasPermission(session, PERMISSIONS.PRODUCTS_CREATE);
}

export function canManageProducts(session: StaffSession): boolean {
  return hasAnyPermission(session, [
    PERMISSIONS.PRODUCTS_UPDATE_ALL,
    PERMISSIONS.PRODUCTS_UPDATE_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_UPDATE_OWN,
    PERMISSIONS.PRODUCTS_DELETE_ALL,
    PERMISSIONS.PRODUCTS_DELETE_BELOW_ROLE,
    PERMISSIONS.PRODUCTS_DELETE_OWN,
  ]);
}
