export type Color = {
    label: string;
    value: string;
}

export const COLORS: readonly Color[] = [
    { label: 'Bleu', value: '#0000FF' },
    { label: 'Aigue-marine', value: '#79F8F8' },
    { label: 'Azur', value: '#007FFF' },
    { label: 'Azur', value: '#1E7FCB' },
    { label: 'Azur clair', value: '#74D0F1' },
    { label: 'Azurin', value: '#A9EAFE' },
    { label: 'Bleu acier', value: '#3A8EBA' },
    { label: 'Bleu ardoise', value: '#686F8C' },
    { label: 'Bleu barbeau', value: '#5472AE' },
    { label: 'Bleu canard', value: '#048B9A' },
    { label: 'Bleu céleste', value: '#26C4EC' },
    { label: 'Bleu charrette', value: '#8EA5BC' },
    { label: 'Bleu céruléen', value: '#357AB7' },
    { label: 'Bleu cobalt', value: '#22427C' },
    { label: 'Bleu d\'eau', value: '#B0E0E6' },
    { label: 'Bleu de cobalt', value: '#3D59AB' },
    { label: 'Bleu de Prusse', value: '#003153' },
    { label: 'Bleu denim', value: '#1560BD' },
    { label: 'Bleu égyptien', value: '#1034A6' },
    { label: 'Bleu électrique', value: '#2C75FF' },
    { label: 'Bleu encre', value: '#003366' },
    { label: 'Bleu glacier', value: '#78B7C5' },
    { label: 'Bleu grisé', value: '#6699CC' },
    { label: 'Bleu horizon', value: '#A7BED3' },
    { label: 'Bleu Klein', value: '#002FA7' },
    { label: 'Bleu lavande', value: '#CCCCFF' },
    { label: 'Bleu marine', value: '#03224C' },
    { label: 'Bleu minéral', value: '#6D9BC3' },
    { label: 'Bleu myosotis', value: '#7DC3F7' },
    { label: 'Bleu nuit', value: '#0F056B' },
    { label: 'Bleu océan', value: '#4F97A3' },
    { label: 'Bleu outremer', value: '#120A8F' },
    { label: 'Bleu paon', value: '#067790' },
    { label: 'Bleu pastel', value: '#AEC6CF' },
    { label: 'Bleu pervenche', value: '#8F8CE7' },
    { label: 'Bleu pétrole', value: '#1D4851' },
    { label: 'Bleu roi', value: '#4169E1' },
    { label: 'Bleu saphir', value: '#0131B4' },
    { label: 'Bleu sarcelle', value: '#008080' },
    { label: 'Bleu smalt', value: '#003399' },
    { label: 'Bleu turquoise', value: '#25FDE9' },
    { label: 'Bleu verdâtre', value: '#3D8E8A' },
    { label: 'Bleu vert', value: '#0D98BA' },
    { label: 'Bleu zinc', value: '#4E7F9E' },
    { label: 'Cyan', value: '#00FFFF' },
    { label: 'Cyan turquoise', value: '#00B7EB' },
    { label: 'Indigo', value: '#4B0082' },
    { label: 'Moutarde', value: '#FFDB58' },
    { label: 'Sarcelle', value: '#008080' },
    { label: 'Turquoise', value: '#40E0D0' },
    { label: 'Vert', value: '#008000' },
    { label: 'Amande', value: '#82C46C' },
    { label: 'Chartreuse', value: '#7FFF00' },
    { label: 'Émeraude', value: '#50C878' },
    { label: 'Jade', value: '#00A86B' },
    { label: 'Kaki', value: '#94812B' },
    { label: 'Menthe', value: '#16B84E' },
    { label: 'Menthe à l\'eau', value: '#98FF98' },
    { label: 'Olive', value: '#708238' },
    { label: 'Pistache', value: '#BEF574' },
    { label: 'Vert absinthe', value: '#7FDD4C' },
    { label: 'Vert amande', value: '#87A96B' },
    { label: 'Vert anis', value: '#9FE855' },
    { label: 'Vert bouteille', value: '#096A09' },
    { label: 'Vert céladon', value: '#83A697' },
    { label: 'Vert chartreuse', value: '#CDEB8B' },
    { label: 'Vert citron', value: '#DFFF00' },
    { label: 'Vert d\'eau', value: '#B0F2B6' },
    { label: 'Vert de chrome', value: '#1B4D3E' },
    { label: 'Vert de gris', value: '#95A595' },
    { label: 'Vert forêt', value: '#228B22' },
    { label: 'Vert kaki', value: '#78866B' },
    { label: 'Vert lichen', value: '#9EFD38' },
    { label: 'Vert lime', value: '#32CD32' },
    { label: 'Vert militaire', value: '#4B5320' },
    { label: 'Vert mousse', value: '#679F5C' },
    { label: 'Vert olive', value: '#556B2F' },
    { label: 'Vert opaline', value: '#A9D6A1' },
    { label: 'Vert perroquet', value: '#3AF24B' },
    { label: 'Vert printemps', value: '#00FF7F' },
    { label: 'Vert sapin', value: '#095228' },
    { label: 'Vert sauge', value: '#689D71' },
    { label: 'Vert tilleul', value: '#A8D800' },
    { label: 'Vert Véronèse', value: '#40826D' },
    { label: 'Vert viride', value: '#40826D' },
    { label: 'Vert-de-gris', value: '#95A595' },
    { label: 'Jaune', value: '#FFFF00' },
    { label: 'Abricot', value: '#E67E30' },
    { label: 'Aurore', value: '#F7E967' },
    { label: 'Bistre', value: '#856D4D' },
    { label: 'Blond', value: '#FEE347' },
    { label: 'Bouton d\'or', value: '#FCDC12' },
    { label: 'Canari', value: '#F7E269' },
    { label: 'Chamois', value: '#D0C07A' },
    { label: 'Champagne', value: '#FBE7B2' },
    { label: 'Citron', value: '#FDE910' },
    { label: 'Crème', value: '#FFFDD0' },
    { label: 'Doré', value: '#FFD700' },
    { label: 'Fauve', value: '#AD4F09' },
    { label: 'Flave', value: '#E6E200' },
    { label: 'Froment', value: '#EEDC82' },
    { label: 'Jaune ambre', value: '#F0C300' },
    { label: 'Jaune bouton d\'or', value: '#FCDC12' },
    { label: 'Jaune cadmium', value: '#FFF600' },
    { label: 'Jaune canari', value: '#E7F00D' },
    { label: 'Jaune citron', value: '#FEEF00' },
    { label: 'Jaune d\'or', value: '#E2A000' },
    { label: 'Jaune de chrome', value: '#FFD300' },
    { label: 'Jaune de Naples', value: '#FFF0BC' },
    { label: 'Jaune impérial', value: '#FFE436' },
    { label: 'Jaune jonquille', value: '#F4D03F' },
    { label: 'Jaune mimosa', value: '#FEF86D' },
    { label: 'Jaune moutarde', value: '#C7CF00' },
    { label: 'Jaune pastel', value: '#FDFD96' },
    { label: 'Jaune paille', value: '#F0E36B' },
    { label: 'Jaune sable', value: '#F5DEB3' },
    { label: 'Jonquille', value: '#F4D03F' },
    { label: 'Maïs', value: '#FBEC5D' },
    { label: 'Miel', value: '#FFC30B' },
    { label: 'Nankin', value: '#F7E269' },
    { label: 'Ocre', value: '#DFAF2C' },
    { label: 'Or', value: '#FFD700' },
    { label: 'Or pâle', value: '#E6BE8A' },
    { label: 'Paille', value: '#F7E269' },
    { label: 'Safran', value: '#F4C430' },
    { label: 'Sable', value: '#C2B280' },
    { label: 'Topaze', value: '#FFC87C' },
    { label: 'Beige', value: '#C8AD7F' },
    { label: 'Brou de noix', value: '#6C541E' },
    { label: 'Brun', value: '#5B3A29' },
    { label: 'Brun chocolat', value: '#7B3F00' },
    { label: 'Brun noisette', value: '#8B6C42' },
    { label: 'Brun rouge', value: '#8A3324' },
    { label: 'Cannelle', value: '#7E4A3B' },
    { label: 'Caramel', value: '#9D6B53' },
    { label: 'Café', value: '#462E01' },
    { label: 'Café au lait', value: '#785E2D' },
    { label: 'Cappuccino', value: '#7E5A46' },
    { label: 'Châtaigne', value: '#8C6B5B' },
    { label: 'Chocolat', value: '#5A3A22' },
    { label: 'Cognac', value: '#9C661F' },
    { label: 'Cuivré', value: '#B87333' },
    { label: 'Havane', value: '#9B7E5A' },
    { label: 'Marron', value: '#582900' },
    { label: 'Marron glacé', value: '#82512C' },
    { label: 'Noisette', value: '#955628' },
    { label: 'Noix', value: '#7B5B3A' },
    { label: 'Ocre brun', value: '#8A6F48' },
    { label: 'Sépia', value: '#AE8964' },
    { label: 'Terre d\'ombre', value: '#926D5B' },
    { label: 'Terre de Sienne', value: '#8A4B08' },
    { label: 'Acajou', value: '#88421D' },
    { label: 'Amarante', value: '#91283B' },
    { label: 'Aubergine', value: '#6D071A' },
    { label: 'Bordeaux', value: '#6D071A' },
    { label: 'Bourgogne', value: '#800020' },
    { label: 'Brique', value: '#842E1B' },
    { label: 'Capucine', value: '#FF5E4D' },
    { label: 'Carmin', value: '#960018' },
    { label: 'Cerise', value: '#DE3163' },
    { label: 'Coquelicot', value: '#C60800' },
    { label: 'Corail', value: '#F08080' },
    { label: 'Corail clair', value: '#F08080' },
    { label: 'Corail foncé', value: '#CD5B45' },
    { label: 'Écarlate', value: '#ED0000' },
    { label: 'Fraise', value: '#FC5D5D' },
    { label: 'Framboise', value: '#C72C48' },
    { label: 'Garance', value: '#EE1010' },
    { label: 'Grenat', value: '#6E0B14' },
    { label: 'Groseille', value: '#CF0A2C' },
    { label: 'Incarnadin', value: '#E25822' },
    { label: 'Lie de vin', value: '#AC1E44' },
    { label: 'Magenta', value: '#FF00FF' },
    { label: 'Ponceau', value: '#C72C48' },
    { label: 'Pourpre', value: '#9C005A' },
    { label: 'Prune', value: '#811453' },
    { label: 'Rouge', value: '#FF0000' },
    { label: 'Rouge baiser', value: '#F00020' },
    { label: 'Rouge cardinal', value: '#C41E3A' },
    { label: 'Rouge cerise', value: '#DE3163' },
    { label: 'Rouge cerise foncé', value: '#A91101' },
    { label: 'Rouge coquelicot', value: '#C60800' },
    { label: 'Rouge cramoisi', value: '#DC143C' },
    { label: 'Rouge framboise', value: '#C72C48' },
    { label: 'Rouge grenat', value: '#6E0B14' },
    { label: 'Rouge indien', value: '#CD5C5C' },
    { label: 'Rouge orangé', value: '#FF4500' },
    { label: 'Rouge rubis', value: '#9B111E' },
    { label: 'Rouge sang', value: '#850606' },
    { label: 'Rouge tomate', value: '#DE2916' },
    { label: 'Rubis', value: '#E0115F' },
    { label: 'Sanguine', value: '#850606' },
    { label: 'Tomate', value: '#DE2916' },
    { label: 'Vermillon', value: '#DB1702' },
    { label: 'Vieux rose', value: '#C08081' },
    { label: 'Rose', value: '#FD6C9E' },
    { label: 'Amarante rose', value: '#F19CBB' },
    { label: 'Bois de rose', value: '#B76E79' },
    { label: 'Dragée', value: '#FFB6C1' },
    { label: 'Fuchsia', value: '#FD3F92' },
    { label: 'Lilas', value: '#C8A2C8' },
    { label: 'Mauve', value: '#D473D4' },
    { label: 'Orchidée', value: '#DA70D6' },
    { label: 'Parme', value: '#CFA0E9' },
    { label: 'Pivoine', value: '#D761A4' },
    { label: 'Poudre', value: '#FADADD' },
    { label: 'Rose bonbon', value: '#F9429E' },
    { label: 'Rose clair', value: '#FFB6C1' },
    { label: 'Rose corail', value: '#F08080' },
    { label: 'Rose dragée', value: '#FE95A1' },
    { label: 'Rose framboise', value: '#E30B5D' },
    { label: 'Rose fuchsia', value: '#FF00FF' },
    { label: 'Rose indien', value: '#FF5A9C' },
    { label: 'Rose magenta', value: '#FF0090' },
    { label: 'Rose pastel', value: '#FDDDE6' },
    { label: 'Rose poudré', value: '#FADADD' },
    { label: 'Rose saumon', value: '#FA8072' },
    { label: 'Rose thé', value: '#F4C2C2' },
    { label: 'Rose vif', value: '#FF007F' },
    { label: 'Saumon', value: '#FA8072' },
    { label: 'Vieux rose', value: '#C08081' },
    { label: 'Violet', value: '#7F00FF' },
    { label: 'Améthyste', value: '#9966CC' },
    { label: 'Aubergine', value: '#614051' },
    { label: 'Héliotrope', value: '#DF73FF' },
    { label: 'Lavande', value: '#B57EDC' },
    { label: 'Lavande grise', value: '#C4C3D0' },
    { label: 'Mauve', value: '#D473D4' },
    { label: 'Mûre', value: '#8F00FF' },
    { label: 'Orchidée', value: '#DA70D6' },
    { label: 'Pourpre', value: '#9C005A' },
    { label: 'Prune', value: '#701C1C' },
    { label: 'Violet améthyste', value: '#884DA7' },
    { label: 'Violet de Bayeux', value: '#98777B' },
    { label: 'Violet d\'évêque', value: '#723E64' },
    { label: 'Violet de Parme', value: '#CFA0E9' },
    { label: 'Violet fumé', value: '#5D3FD3' },
    { label: 'Violet impérial', value: '#660099' },
    { label: 'Violet lavande', value: '#967BB6' },
    { label: 'Violet lilas', value: '#B666D2' },
    { label: 'Violet mauve', value: '#915F6D' },
    { label: 'Violet orchidée', value: '#DA70D6' },
    { label: 'Violet pastel', value: '#D8BFD8' },
    { label: 'Violet prune', value: '#6C3082' },
    { label: 'Violet pourpre', value: '#A020F0' },
    { label: 'Blanc', value: '#FFFFFF' },
    { label: 'Blanc cassé', value: '#F8F8FF' },
    { label: 'Blanc crème', value: '#FFFDD0' },
    { label: 'Blanc d\'ivoire', value: '#FFFFF0' },
    { label: 'Blanc de lune', value: '#F1E9D2' },
    { label: 'Blanc neige', value: '#FFFAFA' },
    { label: 'Blanc perle', value: '#F0EAD6' },
    { label: 'Coquille d\'œuf', value: '#FDE9E0' },
    { label: 'Écru', value: '#FEFEE2' },
    { label: 'Ivoire', value: '#FFFFF0' },
    { label: 'Lin', value: '#FAF0E6' },
    { label: 'Nacre', value: '#FDF5E6' },
    { label: 'Perle', value: '#EAE0C8' },
    { label: 'Argent', value: '#C0C0C0' },
    { label: 'Ardoise', value: '#708090' },
    { label: 'Cendré', value: '#B9B9B9' },
    { label: 'Étain', value: '#7F7F7F' },
    { label: 'Fumée', value: '#9EA0A1' },
    { label: 'Grège', value: '#BBAE98' },
    { label: 'Gris', value: '#808080' },
    { label: 'Gris acier', value: '#B0C4DE' },
    { label: 'Gris ardoise', value: '#708090' },
    { label: 'Gris argent', value: '#C0C0C0' },
    { label: 'Gris cendré', value: '#C0C0C0' },
    { label: 'Gris clair', value: '#D3D3D3' },
    { label: 'Gris de Payne', value: '#536878' },
    { label: 'Gris de perle', value: '#CECECE' },
    { label: 'Gris éléphant', value: '#B8B8B8' },
    { label: 'Gris fer', value: '#7F7F7F' },
    { label: 'Gris fumée', value: '#9EA0A1' },
    { label: 'Gris galet', value: '#B0B0B0' },
    { label: 'Gris graphite', value: '#474A51' },
    { label: 'Gris souris', value: '#9E9E9E' },
    { label: 'Gris taupe', value: '#8B8589' },
    { label: 'Noir', value: '#000000' },
    { label: 'Noir charbon', value: '#36454F' },
    { label: 'Noir d\'ivoire', value: '#292421' },
    { label: 'Noir de jais', value: '#1C1C1C' },
    { label: 'Noir réglisse', value: '#2E2E2E' },
    { label: 'Taupe', value: '#8B8589' },
    { label: 'Anthracite', value: '#303030' },
    { label: 'Arlequin', value: '#3FFF00' },
    { label: 'Banane', value: '#FFE135' },
    { label: 'Béryl', value: '#DEE5C0' },
    { label: 'Bitume', value: '#4B3621' },
    { label: 'Cacao', value: '#614B3A' },
    { label: 'Céladon', value: '#ACE1AF' },
    { label: 'Cendre bleue', value: '#7D7F8A' },
    { label: 'Chair', value: '#FAD6A5' },
    { label: 'Châtaigne clair', value: '#CD853F' },
    { label: 'Ciel', value: '#87CEEB' },
    { label: 'Citrouille', value: '#FF7518' },
    { label: 'Cobalt clair', value: '#3D59AB' },
    { label: 'Coquelicot foncé', value: '#A91D11' },
    { label: 'Cramoisi', value: '#DC143C' },
    { label: 'Ébène', value: '#555D50' },
    { label: 'Écume', value: '#CFFFE5' },
    { label: 'Étain clair', value: '#D2D2D2' },
    { label: 'Flamme', value: '#E25822' },
    { label: 'Fraise écrasée', value: '#A42424' },
    { label: 'Fumée bleue', value: '#6699CC' },
    { label: 'Galet', value: '#B0B0B0' },
    { label: 'Glace', value: '#D6FFFA' },
    { label: 'Glycine', value: '#C9A0DC' },
    { label: 'Grenadine', value: '#E9383F' },
    { label: 'Guimauve', value: '#F3CFC6' },
    { label: 'Horizon', value: '#A7C7E7' },
    { label: 'Lagon', value: '#5BC0BE' },
    { label: 'Mandarine', value: '#F37A48' },
    { label: 'Mastic', value: '#B3B7A5' },
    { label: 'Minuit', value: '#191970' },
    { label: 'Myrtille', value: '#4F86F7' },
    { label: 'Neige', value: '#FFFAFA' },
    { label: 'Nuit', value: '#0F056B' },
    { label: 'Nuage', value: '#CFCFC4' },
    { label: 'Océan profond', value: '#005F6A' },
    { label: 'Opale', value: '#A8C3BC' },
    { label: 'Pêche', value: '#FFE5B4' },
    { label: 'Pervenche', value: '#CCCCFF' },
    { label: 'Platine', value: '#E5E4E2' },
    { label: 'Poivre', value: '#4B4B4B' },
    { label: 'Poussière', value: '#B2996E' },
    { label: 'Quartz', value: '#D9D9F3' },
    { label: 'Réglisse', value: '#1A1110' },
    { label: 'Rouille', value: '#B7410E' },
    { label: 'Rubis foncé', value: '#843F5B' },
    { label: 'Sable chaud', value: '#D2B48C' },
    { label: 'Saphir', value: '#0F52BA' },
    { label: 'Tourterelle', value: '#B7A99A' },
    { label: 'Émeraude foncé', value: '#046307' },
    { label: 'Bleu abysse', value: '#00008B' },
    { label: 'Bleu acier clair', value: '#7A9EBD' },
    { label: 'Bleu agave', value: '#5F9EA0' },
    { label: 'Bleu de minuit', value: '#191970' },
    { label: 'Bleu denim clair', value: '#5DADEC' },
    { label: 'Bleu dragée', value: '#B5D0E3' },
    { label: 'Bleu fumé', value: '#7A89B8' },
    { label: 'Bleu givré', value: '#D6EAF8' },
    { label: 'Bleu jean', value: '#3B5998' },
    { label: 'Bleu liseron', value: '#6A5ACD' },
    { label: 'Bleu paon foncé', value: '#004B5C' },
    { label: 'Bleu piscine', value: '#38B6FF' },
    { label: 'Bleu porcelaine', value: '#B0C4DE' },
    { label: 'Bleu poussière', value: '#AEC6CF' },
    { label: 'Bleu glacier foncé', value: '#5F9EA0' },
    { label: 'Bleu plomb', value: '#5A6372' },
    { label: 'Bleu tourterelle', value: '#AAB7C4' },
    { label: 'Vert absinthe clair', value: '#C5E384' },
    { label: 'Vert avocat', value: '#568203' },
    { label: 'Vert bambou', value: '#7A9E7E' },
    { label: 'Vert bouteille clair', value: '#4F7942' },
    { label: 'Vert cactus', value: '#587D71' },
    { label: 'Vert chlorophylle', value: '#4AFF00' },
    { label: 'Vert cyprès', value: '#1C352D' },
    { label: 'Vert des bois', value: '#2E4B3C' },
    { label: 'Vert eucalyptus', value: '#44D7A8' },
    { label: 'Vert givré', value: '#D0F0C0' },
    { label: 'Vert grisé clair', value: '#A9BA9D' },
    { label: 'Vert jade foncé', value: '#00A86B' },
    { label: 'Vert loden', value: '#5B6A44' },
    { label: 'Vert malachite', value: '#0BDA51' },
    { label: 'Vert menthe glacée', value: '#AAF0D1' },
    { label: 'Vert olive foncé', value: '#556B2F' },
    { label: 'Vert pomme', value: '#8DB600' },
    { label: 'Vert prairie', value: '#7BB661' },
    { label: 'Vert réséda', value: '#6C7C59' },
    { label: 'Jaune beurre', value: '#F5E050' },
    { label: 'Jaune curry', value: '#CFAE00' },
    { label: 'Jaune pastel clair', value: '#FFFACD' },
    { label: 'Jaune soufre', value: '#F5DE00' },
    { label: 'Jaune tournesol', value: '#FFC512' },
    { label: 'Brun acajou', value: '#4E2715' },
    { label: 'Brun cannelle', value: '#7E4A3B' },
    { label: 'Brun cuivré', value: '#8C4A2F' },
    { label: 'Brun tabac', value: '#6F4E37' },
    { label: 'Brun terre', value: '#7B4B3A' },
    { label: 'Rouge brique clair', value: '#B22222' },
    { label: 'Rouge grenade', value: '#7B112C' },
    { label: 'Rouge opéra', value: '#C41E3A' },
    { label: 'Rouge piment', value: '#D3212D' },
    { label: 'Rouge profond', value: '#8B0000' },
    { label: 'Rouge vermillon clair', value: '#FF5B00' },
    { label: 'Rose antique', value: '#C08081' },
    { label: 'Rose blush', value: '#F4C2C2' },
    { label: 'Rose pastel clair', value: '#FFD1DC' },
    { label: 'Rose pêche', value: '#FAD6A5' },
    { label: 'Rose quartz', value: '#F7CAC9' },
    { label: 'Rose vif foncé', value: '#C71585' },
    { label: 'Violet aubergine', value: '#614051' },
    { label: 'Violet clair', value: '#B19CD9' },
    { label: 'Violet iris', value: '#5A4FCF' },
    { label: 'Violet nuit', value: '#2E1A47' },
    { label: 'Blanc albâtre', value: '#F2F0E6' },
    { label: 'Blanc cassé chaud', value: '#FAF3E0' },
    { label: 'Blanc fumé', value: '#F5F5F5' },
    { label: 'Gris béton', value: '#8D918D' },
    { label: 'Gris colombe', value: '#C7C7C7' },
    { label: 'Gris fumée bleuté', value: '#8A9BA8' },
    { label: 'Gris lunaire', value: '#DCDCDC' },
    { label: 'Gris perle bleuté', value: '#D3DCE3' },
    { label: 'Noir graphite', value: '#2F4F4F' },
    { label: 'Taupe rosé', value: '#A89F91' },
    { label: 'Sable rosé', value: '#DAB89B' },
    { label: 'Ivoire rosé', value: '#F8E8E0' },
    { label: 'Vert-de-gris bleu', value: '#7F9C96' },
    { label: 'Bleu-gris', value: '#6699CC' },
    { label: 'Rouge-violet', value: '#C71585' },
    { label: 'Jaune-vert', value: '#9ACD32' },
    { label: 'Brun-roux', value: '#A52A2A' },
    { label: 'Rose-violet', value: '#DB7093' },
    { label: 'Bleu roi foncé', value: '#27408B' },
    { label: 'Bleu nuit foncé', value: '#0A0A5F' },
    { label: 'Bleu givre', value: '#E0FFFF' },
    { label: 'Vert pin', value: '#01796F' },
    { label: 'Vert forêt sombre', value: '#0B3D0B' },
    { label: 'Jaune miel', value: '#FFC30B' },
    { label: 'Jaune vanille', value: '#F3E5AB' },
    { label: 'Brun sable', value: '#C2B280' },
    { label: 'Brun cuir', value: '#8B5A2B' },
    { label: 'Rouge corail vif', value: '#FF4040' },
    { label: 'Rouge terre cuite', value: '#CC4E3C' },
    { label: 'Rose nude', value: '#E3BC9A' },
    { label: 'Violet fumé clair', value: '#A497BD' },
    { label: 'Gris perle rosé', value: '#D8CFC4' },
] as const;

const COLOR_NAME_TO_HEX: Record<string, string> = COLORS.reduce((acc, color) => {
    acc[color.label] = color.value;
    return acc;
}, {} as Record<string, string>);

const COLOR_HEX_TO_LABEL: Record<string, string> = COLORS.reduce((acc, color) => {
    acc[color.value] = color.label;
    return acc;
}, {} as Record<string, string>);

export function getHexCodeByName(label: string): string | undefined {
    return COLOR_NAME_TO_HEX[label];
}

export function getNameByHexCode(value: string): string | undefined {
    return COLOR_HEX_TO_LABEL[value];
}

export function getColorNameSuggestions(query: string): string[] {
    if(!query) return [];
    const lowerQuery = query.toLowerCase();
    return COLORS.filter(color => color.label.toLowerCase().startsWith(lowerQuery)).map(color => color.label);
}

function normalizeColorKey(value: string | null | undefined) {
    return (value ?? "")
        .normalize("NFD")
        .replace(/[\u0300-\u036f]/g, "")
        .trim()
        .toLowerCase()
        .replace(/\s+/g, " ");
}

export function resolveColorHex(value: string | null | undefined): string | null {
    const trimmedValue = (value ?? "").trim();

    if (!trimmedValue) {
        return null;
    }

    const exactHex = trimmedValue.match(/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/);
    if (exactHex) {
        const hexValue = trimmedValue.toUpperCase();
        return hexValue.length === 4
            ? `#${hexValue[1]}${hexValue[1]}${hexValue[2]}${hexValue[2]}${hexValue[3]}${hexValue[3]}`
            : hexValue;
    }

    const normalizedValue = normalizeColorKey(trimmedValue);
    const matchedColor = COLORS.find(
        (color) =>
            normalizeColorKey(color.label) === normalizedValue ||
            normalizeColorKey(color.value) === normalizedValue,
    );

    return matchedColor?.value ?? null;
}
